T1924 wp sponsorships not visible in my compassion (#1992)
* Fix res_partner_test.py

The order of imports prevented the PartnerTest class from bein initialised properly (in test mode).

* Fix import mock

* Fix _get_partner_for_contract call which had a useless argument

File "/home/zivi/Development/odoo-compassion/odoo/odoo14/addons-compassion-switzerland/compassion-modules/sponsorship_compassion/models/contract_group.py", line 70, in _get_partner_for_contract
    return super(ContractGroup, self)._get_partner_for_contract(contract, gift_wizard)
TypeError: _get_partner_for_contract() takes 2 positional arguments but 3 were given

* Fix test_sponsorship_compassion

* Fix pre-commit

* Impl migration to fix SWP contracts

* Make fix cleaner and start checking on create

* Impl onchange method to set SWP consistently

* Fix migration missing steps

* Fix pre-commit

* Fix pre-commit

* Revert incorrect unit test fix

* Propose improved migration for SWP