T1955 - Fix unit tests (#1990)
* Fix res_partner_test.py

The order of imports prevented the PartnerTest class from bein initialised properly (in test mode).

* Fix import mock

* Fix _get_partner_for_contract call which had a useless argument

File "/home/zivi/Development/odoo-compassion/odoo/odoo14/addons-compassion-switzerland/compassion-modules/sponsorship_compassion/models/contract_group.py", line 70, in _get_partner_for_contract
    return super(ContractGroup, self)._get_partner_for_contract(contract, gift_wizard)
TypeError: _get_partner_for_contract() takes 2 positional arguments but 3 were given

* Fix test_sponsorship_compassion

* Fix pre-commit

* Fix tests

* Run pre-commit