T1715 - FCPs are wrongly marked as suspended (#1994)
* Fix res_partner_test.py

The order of imports prevented the PartnerTest class from bein initialised properly (in test mode).

* Fix import mock

* Fix _get_partner_for_contract call which had a useless argument

File "/home/zivi/Development/odoo-compassion/odoo/odoo14/addons-compassion-switzerland/compassion-modules/sponsorship_compassion/models/contract_group.py", line 70, in _get_partner_for_contract
    return super(ContractGroup, self)._get_partner_for_contract(contract, gift_wizard)
TypeError: _get_partner_for_contract() takes 2 positional arguments but 3 were given

* Fix test_sponsorship_compassion

* Fix pre-commit

* Impl cron job; to test

* Start implementing tests; to test

* Impl test for sync_projects_from_gmc

* Fix pre-commit

* Fix last_lifecycle_id not stored exception

* Improve cron description

* Set cron active by default

* Revert gift_wizard contract_group change

* Move sync_projects_from_gmc to sponsorship_compassion module

* Start impl sync_projects_from_gmc

---------

Co-authored-by: ecino <ecino@users.noreply.github.com>