T1959 reconciliation is not behaving as it should (#1996)
* Fix res_partner_test.py

The order of imports prevented the PartnerTest class from bein initialised properly (in test mode).

* Fix import mock

* Fix _get_partner_for_contract call which had a useless argument

File "/home/zivi/Development/odoo-compassion/odoo/odoo14/addons-compassion-switzerland/compassion-modules/sponsorship_compassion/models/contract_group.py", line 70, in _get_partner_for_contract
    return super(ContractGroup, self)._get_partner_for_contract(contract, gift_wizard)
TypeError: _get_partner_for_contract() takes 2 positional arguments but 3 were given

* Fix test_sponsorship_compassion

* Fix pre-commit

* Strict ref matching in progress

* Impl backend for strict payment reconciliation on ref/label

* Start impl strict ref matching UI

* Add strict_reference_matching button on reconcile model view

* Fix strict_reference_matching

* Start impl unit tests

* Start impl unit tests

* Impl tests in progress

* Test _filter_reconciliations_strict_ref

* Improve _filter_reconciliations_strict_ref + unit tests

* Fix pre-commit

* Restore incorrect unit test fix

* Re-enable previous tests

* Fix aml_ids which were not ids bug